version: '3.8'

services:
   latticeapi-nestjs-app:
    build: .
    ports: 
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate dev && npm run start:dev"
    env_file:
      - .env
