services:
  launchpad-api:
    build: .
    image: launchpad-api:latest
    container_name: launchpad-api

    restart: unless-stopped

    env_file:
      - .env

    networks:
      - production

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.launchpad-api.rule=Host(`launchpad-api.terravest.capital`)"
      - "traefik.http.routers.launchpad-api.entrypoints=websecure"
      - "traefik.http.routers.launchpad-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.launchpad-api.loadbalancer.server.port=8000"

networks:
  production:
    external: true