version: '3.8'

services:
  nest-app:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:uutb@lattice-dev.cfe0ysqi6mn5.ap-southeast-1.rds.amazonaws.com:5432/lattice_db?schema=lattice
      - PORT=8000
      - JWT_REFRESH_SECRET=1234
      - JWT_SECRET=123
      - DEFAULT_PASSWORD=1234567890
    ports: 
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
