version: '3.8'

services:
   latticeapi-nestjs-app:
    build: .
    ports: 
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    #command: sh -c "npx prisma migrate deploy && npm run start:dev"
    # command: sh ./wait-for-it.sh
    env_file:
      - .env
