export const softDeleteModels = [
  'User',
  'Role',
  'Permission',
  'Menu',
  'Chain',
  'Category',
  'ProjectReviewLog',
  'ReviewVerificationLog',
  'ProjectOwnerVerification',
  'FileLog',
  'Social',
  'Verification',
  'Project',
  'ProjectType',
  'Presales',
];
